import 'translation_keys.dart' as translation;

class Ar {
  Map<String, String> get messages => {
    translation.title: 'كارت عراقي',
    translation.appLanguage: 'لغة التطبيق',
    translation.settings: 'إعدادات',
    translation.home: 'بيت',
    translation.cards: 'البطاقات',
    translation.profile: 'حساب تعريفي',
    translation.recommended: 'مُستَحسَن',
    translation.featured: 'متميز',
    translation.firstName: 'الاسم الأول',
    translation.lastName: 'اسم العائلة',
    translation.emailAddress: 'عنوان البريد الإلكتروني',
    translation.mobileNumber: 'رقم الهاتف المحمول',
    translation.address: 'عنوان',
    translation.state: 'ولاية',
    translation.zipCode: 'الرمز البريدي',
    translation.city: 'مدينة',
    translation.country: 'دولة',
    translation.updateProfile: 'تحديث الملف',
    translation.firstNameValidation: 'الرجاء إدخال الاسم الأول.',
    translation.lastNameValidation: 'الرجاء إدخال الاسم الأخير.',
    translation.emailValidation: 'الرجاء إدخال عنوان البريد الإلكتروني.',
    translation.invalidEmailValidation: 'الرجاء إدخال عنوان بريد إلكتروني صالح.',
    translation.phoneValidation: 'الرجاء إدخال رقم الهاتف المحمول.',
    translation.invalidPhoneValidation: 'الرجاء إدخال رقم هاتف محمول صحيح.',
    translation.addressValidation: 'الرجاء إدخال العنوان.',
    translation.stateValidation: 'الرجاء إدخال الولاية.',
    translation.zipValidation: 'الرجاء إدخال الرمز البريدي.',
    translation.cityValidation: 'الرجاء إدخال المدينة.',
    translation.countryValidation: 'الرجاء إدخال الدولة.',
  };
}