import 'translation_keys.dart' as translation;

class En {
  Map<String, String> get messages => {
    translation.title: 'Iraqi Card',
    translation.appLanguage: 'App Language',
    translation.settings: 'Settings',
    translation.home: 'Home',
    translation.cards: 'Cards',
    translation.profile: 'Profile',
    translation.recommended: 'Recommended',
    translation.featured: 'Featured',
    translation.firstName: 'First Name',
    translation.lastName: 'Last Name',
    translation.emailAddress: 'Email Address',
    translation.mobileNumber: 'Mobile Number',
    translation.address: 'Address',
    translation.state: 'State',
    translation.zipCode: 'Zip Code',
    translation.city: 'City',
    translation.country: 'Country',
    translation.updateProfile: 'Update Profile',
    translation.firstNameValidation: 'Please enter first name.',
    translation.lastNameValidation: 'Please enter last name.',
    translation.emailValidation: 'Please enter email address.',
    translation.invalidEmailValidation: 'Please enter valid email address.',
    translation.phoneValidation: 'Please enter mobile number.',
    translation.invalidPhoneValidation: 'Please enter valid mobile number.',
    translation.addressValidation: 'Please enter address.',
    translation.stateValidation: 'Please enter state.',
    translation.zipValidation: 'Please enter zip code.',
    translation.cityValidation: 'Please enter city.',
    translation.countryValidation: 'Please enter country.',
  };
}