import 'translation_keys.dart' as translation;

class En {
  Map<String, String> get messages => {
        translation.title: 'Iraqi Card',
        translation.appLanguage: 'App Language',
        translation.settings: 'Settings',
        translation.home: 'Home',
        translation.cards: 'Cards',
        translation.profile: 'Profile',
        translation.recommended: 'Recommended',
        translation.featured: 'Featured',
        translation.username: 'Username',
        translation.firstName: 'First Name',
        translation.lastName: 'Last Name',
        translation.emailAddress: 'Email Address',
        translation.password: 'Password',
        translation.confirmPassword: 'Confirm password',
        translation.mobileNumber: 'Mobile Number',
        translation.address: 'Address',
        translation.state: 'State',
        translation.zipCode: 'Zip Code',
        translation.city: 'City',
        translation.country: 'Country',
        translation.buttonUpdateProfile: 'Update Profile',
        translation.firstNameValidation: 'Please enter first name.',
        translation.lastNameValidation: 'Please enter last name.',
        translation.emptyEmailValidation: 'Please enter email address.',
        translation.invalidEmailValidation: 'Please enter valid email address.',
        translation.phoneValidation: 'Please enter mobile number.',
        translation.invalidPhoneValidation: 'Please enter valid mobile number.',
        translation.addressValidation: 'Please enter address.',
        translation.stateValidation: 'Please enter state.',
        translation.zipValidation: 'Please enter zip code.',
        translation.cityValidation: 'Please enter city.',
        translation.countryValidation: 'Please enter country.',
        translation.titleEditProfile: 'Edit Profile',
        translation.emptyPasswordValidation: 'Please enter password.',
        translation.emptyConfirmPasswordValidation: 'Please enter confirm password.',
        translation.wrongConfirmPasswordValidation: 'Password and confirm password does not match.',
        translation.emptyUsernameValidation: 'Please enter username.',
        translation.passwordLengthValidation: 'Password length must be at least 6 characters.',
        translation.buttonLogin: 'Login',
        translation.buttonSignup: 'Signup',
      };
}
